default:
  image: ibains007/docker-cli:latest
  services:
    - name: docker:18-dind
      entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    
stages:
  - unit_tests
  - build_image
  - push_image

unit_tests:
  stage: unit_tests
  image: maven:3.8-openjdk-8-slim 
  script: 
    - cd spring
    - mvn test

build_image:
  stage: build_image
  services:
    - name: docker:18-dind
  dependencies:
    - unit_tests
  script: 
    - cd spring
    - docker build -t ibains007/notejam::"$CI_COMMIT_SHORT_SHA" .

push_image:
  stage: push_image
  services:
    - name: docker:18-dind
  dependencies:
    - build_image
  script: 
    - docker login -u $user -p $pass
    - docker push ibains007/notejam::"$CI_COMMIT_SHORT_SHA"



